### ISSUE TITLE
Questions about legal entity requirements

### ISSUE THREAD

**Issue by scottgonzalez** [berneout/public-public-license#2]
> Legal entities, but not natural persons, that would exercise this
> permission

Does "this permission" refer to the entirety of the preceeding paragraph as quoted below?

> Redistribution and use in source and binary forms, with or without
> modification, are permitted provided that the following conditions are
> met:

If so, doesn't that include mere use of unmodified code?

> must propose a dated change to this file

Does "this file" refer to the standalone license file, or is the license expected to be copied into each individual source file? I know some large projects do this, but the majority of open source projects don't.

> identifying
> themselves by legal name, form, jurisdiction, and a contact e-mail
> address to those publicly maintaining this software.

This sounds like the change needs to be upstream, even if the modifications aren't. Is that correct?

> The change will be
> published with this software.

Does "the change" refer solely to the addition of the legal entity's information and not the actual code changes?

**Comment by kemitchell** [comment]
In order:

1.  "permission" refers to the verb "permitted" in the paragraph above.

2.  Yes. The permission covers use of unmodified code.

3.  The `LICENSE` file, or whatever it happens to be called in the repository.

4.  What modifications?

5.  Yes.  Just the appending of legal entity info.
